### ISSUE TITLE
素数统计例子中，CPU和GPU计算结果不一致

### ISSUE THREAD

**Issue by xujinzh** [taichi-dev/faster-python-with-taichi#1]
针对素数统计例子（https://github.com/taichi-dev/faster-python-with-taichi/blob/main/count_primes.py），我测试了使用taichi在CPU和GPU上计算10000_0000以内的素数个数，发现CPU统计结果为5761455，而GPU统计结果为5761489?

**Comment by neozhaoliang** [comment]
感谢您提的 issue，经过我的复现 `n` 等于 1 亿时确实 GPU 上得到的结果比 CPU 多 1。问题应该出在 `n**0.5` 这个地方 `sqrt` 运算在 GPU 上的精度不够导致的。你可以试试这里给的解决方法：
https://github.com/taichi-dev/taichi/issues/5935

**Comment by xujinzh** [comment]
> 感谢您提的 issue，经过我的复现 `n` 等于 1 亿时确实 GPU 上得到的结果比 CPU 多 1。问题应该出在 `n**0.5` 这个地方 `sqrt` 运算在 GPU 上的精度不够导致的。你可以试试这里给的解决方法： [taichi-dev/taichi#5935](https://github.com/taichi-dev/taichi/issues/5935)

好的，谢谢回复。
